package edu.buffalo.cse.cse486586.simpledht;

public enum MessageType {
	JOIN_REQUEST, NODE_PROPERTIES_MODIFICATION, INSERT, QUERY_REQUEST, DELETE_REQUEST, QUERY_REQUEST_ALL, DELETE_REQUEST_ALL,
	QUERY_RESPONSE
}
